# ---------- Builder ----------
FROM swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/golang:1.24-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go env -w GO111MODULE=on \
 && go env -w GOPROXY=https://goproxy.cn,direct \
 && go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -ldflags "-s -w" -o iptv main.go


# ---------- Runtime ----------
FROM alpine:latest

ENV TZ=Asia/Shanghai
ENV ANDROID_HOME=/opt/android-sdk
ENV ANDROID_SDK_ROOT=/opt/android-sdk
ENV PATH=$PATH:/opt/android-sdk/build-tools


WORKDIR /app
VOLUME /config
EXPOSE 80 8080

# 基础依赖
RUN apk add --no-cache \
    openjdk17 \
    bash \
    curl \
    wget \
    unzip \
    zip \
    ffmpeg \
    sqlite \
    libwebp-tools \
    libc6-compat \
    libstdc++ \
    tzdata \
    && cp /usr/share/zoneinfo/${TZ} /etc/localtime \
    && echo ${TZ} > /etc/timezone \
    && rm -rf /var/lib/apt/lists/*

# Android build-tools（apksigner / zipalign）
RUN mkdir -p ${ANDROID_HOME}/build-tools \
 && curl -L -o /tmp/build-tools.zip \
    https://dl.google.com/android/repository/build-tools_r33.0.2-linux.zip \
 && unzip /tmp/build-tools.zip -d  /tmp/build-tools \
 && mv /tmp/build-tools/android-13/* \
       ${ANDROID_HOME}/build-tools \
 && rm -rf /tmp/build-tools*

# apktool
COPY apktool/apktool /usr/bin/apktool
COPY apktool/apktool.jar /usr/bin/apktool.jar
RUN chmod +x /usr/bin/apktool*

# 应用资源
COPY client /client
COPY static /app/static
COPY database /app/database
COPY logo /app/logo

COPY config.yml README.md dictionary.txt alias.json ChangeLog.md Version license start MyTV.apk keystore.p12 /app/
COPY license_all/Version_lic /app/Version_lic

# Go 程序
COPY --from=builder /app/iptv /app/iptv

CMD ["./start"]
