FROM --platform=$BUILDPLATFORM swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/golang:1.24-alpine AS builder

ARG TARGETARCH

WORKDIR /app

COPY go.mod go.sum ./
RUN go env -w GO111MODULE=on 
RUN go env -w  GOPROXY=https://goproxy.cn,direct 
RUN go mod download

COPY . .

RUN case "$TARGETARCH" in \
      amd64) cp ./license/license_amd64 ./license ;; \
      arm64) cp ./license/license_arm64 ./license ;; \
      arm)   cp ./license/license_armv7 ./license ;; \
      *) echo "未知架构: $TARGETARCH" && exit 1 ;; \
    esac

# 根据架构交叉编译
RUN case "$TARGETARCH" in \
      amd64) echo "编译 amd64"; GOOS=linux GOARCH=amd64 go build -o iptv main.go ;; \
      arm64) echo "交叉编译 arm64"; GOOS=linux GOARCH=arm64 go build -o iptv main.go ;; \
      arm)   echo "交叉编译 armv7"; GOOS=linux GOARCH=arm GOARM=7 go build -o iptv main.go ;; \
      *) echo "未知架构: $TARGETARCH" && exit 1 ;; \
    esac

RUN chmod +x /app/iptv


FROM swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/alpine:latest

VOLUME /config
WORKDIR /app
EXPOSE 80 8080

ENV TZ=Asia/Shanghai
RUN apk add --no-cache openjdk8 bash curl tzdata sqlite ffmpeg ;\
    cp /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY ./client /client
COPY ./apktool/* /usr/bin/
COPY ./static /app/static
COPY ./database /app/database
COPY ./config.yml /app/config.yml
COPY ./README.md  /app/README.md
COPY ./logo /app/logo
COPY ./ChangeLog.md /app/ChangeLog.md
COPY ./Version /app/Version

RUN chmod 777 -R /usr/bin/apktool* 

COPY --from=builder /app/iptv .
COPY --from=builder /app/license .

CMD ["./iptv"]
