FROM swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go env -w GO111MODULE=on 
RUN go env -w  GOPROXY=https://goproxy.cn,direct 
RUN go mod download

COPY . .

# 根据架构交叉编译
RUN go build -ldflags "-s -w" -o iptv main.go


RUN chmod +x /app/iptv


FROM swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/alpine:latest

ENV TZ=Asia/Shanghai
VOLUME /config
WORKDIR /app
EXPOSE 80 8080

COPY ./client /client
COPY ./apktool/* /usr/bin/
COPY ./static /app/static
COPY ./config.yml /app/config.yml
COPY ./README.md  /app/README.md
COPY ./logo /app/logo
COPY ./dictionary.txt /app/dictionary.txt

RUN apk add --no-cache openjdk8 bash curl tzdata sqlite ffmpeg ;\
    cp /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone ;\
    chmod 777 -R /usr/bin/apktool*
    
COPY ./database /app/database
COPY ./alias.json /app/alias.json
COPY ./ChangeLog.md /app/ChangeLog.md
COPY ./Version /app/Version
COPY ./license_all/Version_lic /app/Version_lic

COPY --from=builder /app/iptv .
COPY ./license .
COPY ./start .

CMD ["./start"]
